name: SF
main: io.github.bugcreatorltq.SFPlugin
version: 1.0
author: lain
commands:
  sf_send:
    description: 发送
    usage: /<command> Player
  sf_accept:
    description: 接收
    usage: /<command>
  sf_ignore:
    description: 拒绝
    usage: /<command>