name: _SF
main: io.github.bugcreatorltq.SFPlugin
version: 1.1
author: lain
commands:
  send:
    description: 发送
    usage: /<command> Player
  sfaccept:
    description: 接收
    usage: /<command>
  sfignore:
    description: 拒绝
    usage: /<command>