name: SF
main: io.github.bugcreatorltq.SFPlugin
version: 1.0
author: lain
commands:
  send:
    description: 发送
    usage: /<command> Player
  accept:
    description: 接收
    usage: /<command>
  ignore:
    description: 拒绝
    usage: /<command>