name: _TPA
main: io.github.bugcreatorltq.TPPlugin
version: 1.4
author: lain
commands:
  tpa:
    description: 传送到一个玩家所在位置
  tpahere:
    description: 传送一个玩家到你所在位置
  tpaccept:
    description: 接受传送请求
  tpaignore:
    description: 拒绝传送请求
