name: TP
main: io.github.bugcreatorltq.TPPlugin
version: 1.1
author: lain
commands:
  tpa:
    description: 传送到一个玩家所在位置
    usage: /<command> Player
  tpahere:
    description: 传送一个玩家到你所在位置
    usage: /<command> Player
  tpaccept:
    description: 接受传送请求
    usage: /<command>
  tpignore:
    description: 拒绝传送请求
    usage: /<command>
