name: _BlockBuilder
main: happecoder.Main
version: 1.17
author: lain
commands:
  array:
    description: You Can Build One array By This Command.
  cup:
    description: You Can Build One cup By This Command.
  box:
    description: You Can Build One box By This Command.
  test:
    description: This Is A Test Command.