name: _BlockBuilder
main: io.github.bugcreatorltq.BlockBuilderPlugin
version: 2.0
author: lain
commands:
  array:
    description: You Can Build One array By This Command.
  cup:
    description: You Can Build One cup By This Command.
  box:
    description: You Can Build One box By This Command.
  line:
    description: You Can Build One line By This Command.
  flat:
    description: You Can Build One flat By This Command.
  test:
    description: This Is A Test Command.